os: osx
# No version of Python is available via virtualenv on OS X workers, see https://github.com/travis-ci/travis-ci/issues/2312
language: generic

env:
  - TOX_ENV=py27-first_startup
  - TOX_ENV=py37-first_startup

install:
  - set -e
  - pip install tox
  - |
    if [ "$TOX_ENV" == "py27-first_startup" ]; then
        # Use this job to test the latest migrations
        wget -q https://github.com/jmchilton/galaxy-downloads/raw/master/db_gx_rev_0141.sqlite
        mv db_gx_rev_0141.sqlite database/universe.sqlite
    elif [ "$TOX_ENV" == "py37-first_startup" ]; then
        # There is now a pre-installed python3 on osx Travis workers, but use this job to test using a conda environment
        MINICONDA_URL="https://repo.anaconda.com/miniconda"
        MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
        curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
        bash $MINICONDA_FILE -b
        . ~/miniconda3/bin/activate
    fi

script: tox -e $TOX_ENV

notifications:
  email: false
